core/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from core import settings
from indexapp import views

from notification.views import showFirebaseJS

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('sentry-debug/', trigger_error),
    # path('admin/view-user-performance/<str:id>', views.view_chart),
    path('admin/', admin.site.urls),
    path('', views.index_view),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.reset, name='reset'),
    path('password-forgot/', views.password_reset),
    path('dashboard/', include('dashboardapp.urls')),
    path('tasks/', include('taskapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('admin-dashboard/', include('admindashboard.urls')),
    path('notification/', include('notification.urls')),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('firebase-messaging-sw.js', showFirebaseJS, name="show_firebase_js"),
    path("admission-apply",views.apply_admission,name="appliction for admission")
    # path('view-chart',include('')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
   import debug_toolbar
   urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
   ]

taskapp/urls.py
from django.urls import path

from taskapp import views

urlpatterns =[
    path('', views.all_tasks),
    path('add-task', views.add_task),
    path('view-task/<str:id>', views.view_single_task),
    path('edit-task/<str:id>', views.edit_task),
    path('task-type/<str:type>', views.task_type),
    path('delete-task/<str:id>', views.delete_task),


    # REPORTING
    path('view-user-reporting-to/', views.contact_user_reporting_to),
    path('view-user-reporting-by/', views.contact_user_reporting_by),
    path('view-user-reporting-by-all-task/<str:user_id>', views.view_reported_by_user_all_task),
    path('view-user-reporting-by-all-project/<str:user_id>', views.view_reported_by_user_all_project),
    path('manage-reporting/', views.manage_reporting),


    # TEAM
    path('view-user-team-member/', views.contact_team_members),


    # ATTENDENCE
    path('mark-attendence/', views.mark_attendence),
    path('mark-attendence-out/', views.mark_attendence_out),
    path('single-user-attendence-detail/', views.single_user_detail_attendence),

    #LEAVE

    path('apply-leave/',views.apply_leave),
    path('user-leave-view/',views.view_leave_detail),




    # path('value/', views.value),
    # path('value1/', views.getting),
    # path('hello/', views.presence_change),

    # path('hello/', views.create_daily_attendence),


    # path('view-chart',views.view_chart),

]

taskapp/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
import uuid
# Create your models here.
from projectapp.models import Project


class ProgrammingLanguage(models.Model):
    language_name=models.CharField(max_length=255)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.language_name

    class Meta:
        verbose_name = 'Languages / Department'

def get_upload_path(instance, filename):
    return 'profile_pictures/{0}/{1}'.format(instance.username, filename)

def get_upload_files_path(instance, filename):
    return 'files/{0}/{1}'.format(instance.task.user.username, filename)

def get_upload_display_profile_path(instance, filename):
    return 'display_profile/{0}/{1}'.format(instance.username, filename)

class User(AbstractUser):
    profile=models.ImageField(null=True,blank=True,upload_to=get_upload_display_profile_path)
    phone_number=models.CharField(max_length=10,null=True,blank=True)
    Alternate_phone_number=models.CharField(max_length=10,null=True,blank=True)
    office_user_id=models.CharField(max_length=255,null=True,blank=True)
    reporting_to=models.CharField(max_length=50,null=True,blank=True)
    is_employee=models.BooleanField(default=False)
    profile_updated=models.BooleanField(default=False)
    display_pic=models.ImageField(blank=True,null=True,upload_to=get_upload_path)
    joining_date=models.DateField(blank=True,null=True)
    leaving_date=models.DateField(blank=True,null=True)
    birthday=models.DateField(blank=True,null=True)
    programming_language=models.ForeignKey(ProgrammingLanguage,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.username


class Attendence(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    attend_date=models.DateField(auto_now_add=True)
    presence=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Leave(models.Model):
    attendence = models.ForeignKey(Attendence, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    leave_period=models.CharField(max_length=20)
    leave_time=models.CharField(max_length=20,null=True,blank=True)
    start_date=models.DateField(auto_now_add=False)
    end_date=models.DateField(auto_now_add=False,null=True,blank=True)
    leave_type=models.CharField(max_length=30)
    leave_description=models.CharField(max_length=100,null=True,blank=True)
    is_pending=models.BooleanField(default=True)
    is_approved=models.BooleanField(default=False)
    is_rejected=models.BooleanField(default=False)



class Events(models.Model):
    title=models.CharField(max_length=30,null=True,blank=True)
    description=models.CharField(max_length=30,null=True,blank=True)
    start_date=models.DateField(auto_now_add=False)
    end_date=models.DateField(auto_now_add=False,null=True,blank=True)



class Detail_attendence(models.Model):
    attendence=models.ForeignKey(Attendence,on_delete=models.CASCADE,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    punch_in=models.TimeField(null=True,blank=True)
    punch_out=models.TimeField(null=True,blank=True)
    attend_date=models.DateField(auto_now_add=True,null=True,blank=True)
    working_hours=models.CharField(max_length=30,null=True,blank=True)


class Reporting(models.Model):
    reported_by=models.CharField(max_length=30,null=True, blank=True)
    existing_reporting_to=models.CharField(max_length=30)
    new_reporting_to=models.CharField(max_length=30)
    duration_from=models.DateField(auto_now_add=False)
    duration_till=models.DateField(auto_now_add=False, null=True, blank=True)

class TaskType(models.Model):
     type_name=models.CharField(max_length=255)
     is_active=models.BooleanField(default=True)
     for_all=models.BooleanField(default=False)
     multiple_language = models.BooleanField(default=False)
     programming_language = models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE, null=True, blank=True)

     def __str__(self):
         return self.type_name

     class Meta:
         verbose_name = 'Task Type'

class multiple_select_language(models.Model):

    task_type=models.ForeignKey(TaskType,on_delete=models.CASCADE,null=True,blank=True)
    programming_language=models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE, null=True, blank=True)


class Task(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    task_type=models.ForeignKey(TaskType,on_delete=models.CASCADE)
    title=models.CharField(max_length=255,default="",null=True,blank=True)
    project=models.ForeignKey(Project,on_delete=models.CASCADE,null=True,blank=True)
    details=models.TextField()
    added_on=models.DateTimeField(auto_now=True)
    updated_on=models.DateTimeField(null=True,blank=True)

    class Meta:

        ordering = ['-id']

    class Meta:
        verbose_name = 'Task'

class task_uploaded_file(models.Model):
     task = models.ForeignKey(Task,on_delete=models.CASCADE)
     uploaded_file = models.FileField(upload_to=get_upload_files_path)
     extension = models.CharField(max_length=255)



system_type_choices= [
        ("Computer", 'Computer'),
        ("Laptop", 'Laptop'),
        ("Macbook", 'MacBook'),
    ]

class  system_detail(models.Model):
    # created_on= models.DateTimeField()
    system_type = models.CharField(max_length=255,choices=system_type_choices,)
    specification = models.TextField()
    system_service = models.TextField(null=True,blank=True)
    system_id=models.CharField(max_length=255,primary_key=True)
    added_on=models.DateTimeField()
    status = models.CharField(max_length=50,default="Free")



    def __str__(self):
        return self.system_id

    class Meta:
        verbose_name = 'System Detail'

assigned_type_choices= [
        ("Temporary", 'Temporary'),
        ("Permanent", 'Permanent'),
    ]
class Assigned_System_Detail(models.Model):
    system_id=models.ForeignKey(system_detail,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    assigned_type = models.CharField(max_length=255, choices=assigned_type_choices, )
    assigned_on = models.DateField()
    returned_on=models.DateField(null=True,blank=True)

    class Meta:
        verbose_name = 'Assigned System Detail'

class Store_password(models.Model):
    password=models.CharField(max_length=255,null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Store Password'



import os
class Walk_in_Interviwee(models.Model):
    name=models.CharField(max_length=255,null=True,blank=True)
    interviwer_name=models.CharField(max_length=255,null=True,blank=True)
    profile=models.CharField(max_length=255,null=True,blank=True)
    experience=models.CharField(max_length=255,null=True,blank=True)
    date=models.DateField(null=True,blank=True)
    status=models.BooleanField(default=False)
    cv=models.FileField(upload_to='cv')

    def __str__(self):
        return self.name

    def __str__(self):
        name, extension = os.path.splitext(self.cv.name)
        return extension




class AddEvent(models.Model):
    title = models.CharField(max_length=25)
    created_at = models.DateField(auto_now=True)
    event_date = models.DateField()
    description = models.TextField(max_length=240)




class Event_photo(models.Model):
    addevent=models.ForeignKey('AddEvent',on_delete=models.CASCADE,null=True,blank=True)
    photo = models.ImageField(upload_to="event_images", null=True, blank=True)
    created_at = models.DateField(auto_now=True)

class Store_token(models.Model):
    user=models.CharField(max_length=255)
    token=models.TextField()
    device=models.CharField(max_length=255,null=True,blank=True)
    os=models.CharField(max_length=255,null=True,blank=True)


class Notification_record(models.Model):
    user=models.ForeignKey('User',on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateField(auto_now=True)
    status=models.CharField(max_length=240)

taskapp/forms.py
from datetime import datetime

from django import forms

from taskapp.models import *




class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = '__all__'

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class TaskUploadedFileForm(forms.ModelForm):
    class Meta:
        model=task_uploaded_file
        exclude =('task', 'uploaded_file', 'extension', )


class ManageReportForm(forms.ModelForm):
    class Meta:
        model= Reporting
        fields=('reported_by','existing_reporting_to','new_reporting_to','duration_from','duration_till')



class AttendenceForm(forms.ModelForm):
    class Meta:
        model=Attendence
        exclude=('attend_date','user')

        def clean_attend_date(self):
            attend_date = self.cleaned_data["attend_date"]
            if Attendence.objects.filter(attend_date=datetime.now().date()).exists():
                raise forms.ValidationError('Cannot Punch In Again!!')
            return attend_date

class LeaveForm(forms.ModelForm):
    class Meta:
        model=Leave
        exclude=('attendence','user','is_pending','is_approved','is_rejected')

templates/taskapp/all_tasks.html
{% extends 'base.html' %}
{% load CustomTaskappTags %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Tasks</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">TASKS</h4>
                  <div class="float-right"><a href="/tasks/add-task" class="btn btn-primary btn-sm">ADD NEW TASK</a>
                  </div>

            </div>
            <div class="card-body">


                <div class="table-responsive">
                    <table id="example" class="display table-responsive-md" style="min-width: 845px">
                        <thead>
                            <tr>
                                <th>Sr. no</th>
                                <th>Task Type</th>
                                <th>Description</th>
                                <th>Added on</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for task in all_task_details %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{task.task_type.type_name}}</td>
                                <td>{{task.details|truncatechars:60}} <a href="#view_detail_{{task.id}}" data-toggle="modal" data-target="#view_detail_{{task.id}}" class="text-info"> view more</a></td>
                                <td>{{task.added_on}}</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="/tasks/view-task/{{task.id}}" class="btn btn-sm btn-primary">VIEW</a>
                                        {{task.id|check_edit_able}}
<!--                                        <a href="/tasks/edit-task/{{task.id}}" class="btn btn-sm btn-success">EDIT</a>-->

                                        <a href="/tasks/delete-task/{{task.id}}" class="btn btn-sm btn-danger">DELETE</a>
                                    </div>
                                </td>


                            </tr>
                             <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true" id="view_detail_{{task.id}}">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">Task Details</h5>
                                            <button type="button" class="close" data-dismiss="modal"><span>&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">{{task.details}} </div>

                                            <div class="modal-footer">
                                            <button type="button" class="btn btn-danger light" data-dismiss="modal">Close</button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}<script type="text/javascript">
$(document).ready(function() {
    $('#example').DataTable();
});
</script>
{% endblock %}

templates/taskapp/edit_task.html
{% extends 'base.html' %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/tasks/">Tasks</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Edit Task</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">ADD NEW TASK</h4>
            </div>
            <div class="card-body">
                <div class="basic-form">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Select Task Type</label>
                            <select class="form-control form-control-lg" name="selected_task_type" required>
                                {% for tasks in all_tasks_type %}
                                <option value="{{tasks.id}}">{{tasks.type_name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Task Details</label>
                            <textarea class="form-control" rows="4" id="comment" name="task_details"></textarea>
                        </div>
                        <button type="submit" class="btn btn-rounded btn-info  btn-md">SUBMIT TASK</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
{% if details_empty %}
swal({
    title: "Failed!",
    text: "task details required!",
    icon: "error",
}); {% endif %}

{% if details_empty %}
swal({
    title: "Sucess!",
    text: "task added successfully !",
    icon: "success",
}); {% endif %}
</script>
{% endblock %}

templates/taskapp/manage_reporting.html
{% extends 'base.html' %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Manage Reporting</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Manage Report</h4>
            </div>
             {% if added %}
                <div class="alert alert-success alert-dismissible fade show">
                    <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <polyline points="9 11 12 14 22 4"></polyline>
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path>
                    </svg>
                    <strong>Success!</strong> Shift Reporting Successfully.
                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                    </button>
                </div>
                {% endif %}

            <div class="card-body">
                <div class="basic-form">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                         {% if reporting_by_user %}
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Reported By</label>
                            <div class="col-sm-9">
                                    {%for i in reporting_by_user%}
                                        <input type="text" class="form-control" name="reported_by" value="{{i.username}}" readonly>
                                    {% endfor %}
                            </div>
                        </div>
                        {%endif%}

                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Reporting To</label>
                            <div class="col-sm-9">

                                <input type="text" class="form-control" name="existing_reporting_to" value="{{request.user}}" >

                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">New Reporting To</label>
                            <div class="col-sm-9">
                                <select class="form-control"  name="new_reporting_to"  id="id_new_reporting_to"  required>
                                     <option value="">---------</option>
                                    {%for i in data%}
                                        <option value={{i.username}}>{{i.username}}</option>
                                        {% endfor %}
                                    </select>
                            </div>
                        </div>

                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Report From</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="duration_from" placeholder="Enter Reporting From"  required>
                            </div>
                        </div>

                          <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Report Till</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="duration_till" placeholder="Enter Reporting Till" required >
                            </div>
                        </div>

                            <div class="container">
                                <div class="btn-block d-sm-flex justify-content-end">
                                     <button type="submit" class="btn btn-sm btn-primary">SAVE</button>&nbsp;
                                     <button type="reset" class="btn btn-sm btn-warning">CANCEL</button>
                             </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
{% endblock %}

templates/taskapp/mark_punchout_attendence.html
{% extends 'base.html' %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="javascript:void(0)">Mark Presence</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Mark Presence</h4>
            </div>
             {% if added %}
                <div class="alert alert-success alert-dismissible fade show">
                    <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <polyline points="9 11 12 14 22 4"></polyline>
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path>
                    </svg>
                    <strong>Success!</strong> Punched Out Successfully.
                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                    </button>
                </div>
                {% endif %}

                <div class="card-body">
                    <div class="basic-form">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-3 col-form-label">Username</label>
                                <div class="col-sm-9">
                                            <input type="text" class="form-control" name="person" value="{{request.user}}" readonly>
                                </div>
                            </div>
                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Date</label>

                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="attend_date" id="date" readonly>
                            </div>
                         </div>
                            <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Punch In Time</label>

                            <div class="col-sm-9">
                                {%for i in a%}
                                <input type="text" class="form-control" name="punch_in" id="punch_in"  value="{{i.punch_in}}"readonly>
                                {%endfor%}
                            </div>
                         </div>
<!--                             <div class="form-group row">-->
<!--                            <label class="col-sm-3 col-form-label">Entry Time</label>-->

<!--                            <div class="col-sm-9">-->
<!--                                <input type="text" class="form-control" name="punch_in" id="currentTime" >-->
<!--                            </div>-->
<!--                         </div>-->
<!--&lt;!&ndash;                             <div class="form-group mb-0">&ndash;&gt;-->
<!--                                    <div class="radio">-->
<!--                                        <label><input type="radio" name="puch_in">Punch In</label>-->
<!--                                        <div id="show_punch_in" class="pt-1"> <label>Entry Time</label>-->
<!--                                            <input type="text" class="form-control" name="punch_in" value="a"></div>-->
<!--                                    </div>-->
<!--                             <div class="form-group mb-0">-->
<!--                            <input type="button"  class="btn btn-sm btn-secondary" name="punch_in" value="Punch In" onclick="ShowHideDiv(this)">-->
<!--                                 <div id="dvPunchin" style="display: none">-->
<!--                                    <input type="text" class="form-control" id="textInput" value="{{punch_in_now}}" />-->
<!--                                 </div>-->
<!--                                   </div>-->

<!--                                    <div class="radio">-->
<!--                                        <label><input type="radio" name="punch_out" >Punch Out</label>-->
<!--                                        <div id="show_punch_out" class="pt-1"> <label>Exit Time</label>-->
<!--                                            <input type="text" class="form-control" name="punch_out" value="b"></div>-->
<!--                                    </div>-->


<!--                        <div class="form-group row">-->
<!--                            <label class="col-sm-3 col-form-label"> </label>-->
<!--                            <div class="col-sm-9">-->
<!--                                <select class="form-control"  name="new_repo"  id="id_new_reporting_to"  required>-->
<!--                                     <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--                                    {%for i in data%}-->
<!--                                        <option value={{i.username}}>{{i.username}}</option>-->
<!--                                        {% endfor %}-->
<!--                                    </select>-->
<!--                            </div>-->
<!--                        </div>-->

<!--                         <div class="form-group row">-->
<!--                            <label class="col-sm-3 col-form-label">Report From</label>-->
<!--                            <div class="col-sm-9">-->
<!--                                <input type="date" class="form-control" name="duration_from" placeholder="Enter Reporting From"  required>-->
<!--                            </div>-->
<!--                        </div>-->

<!--                          <div class="form-group row">-->
<!--                            <label class="col-sm-3 col-form-label">Report Till</label>-->
<!--                            <div class="col-sm-9">-->
<!--                                <input type="date" class="form-control" name="duration_till" placeholder="Enter Reporting Till" required >-->
<!--                            </div>-->
<!--                        </div>-->

                            <div class="container">
                                <div class="btn-block d-sm-flex justify-content-end">
                                     <button type="submit" class="btn btn-sm btn-primary">Punch Out</button>&nbsp;
                                     <button type="reset" class="btn btn-sm btn-warning">CANCEL</button>
                             </div>
                            </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

<!--     function ShowHideDiv(btnPunchin) {-->
<!--        var dvPassport = document.getElementById("dvPunchin");-->
<!--        dvPassport.style.display = btnPunchin.value == "Punch In" ? "block" : "none";-->
<!--    }-->

let dateInput = document.getElementById('date');
dateInput.valueAsDate = new Date();

<!--var today = new Date();-->
<!--var time = today. getHours() + ":" + today. getMinutes() + ":" + today. getSeconds() + ":" + today.getMilliseconds();-->
<!--document. getElementById("currentTime"). value = time;-->



</script>
{% endblock %}