admindashboard/urls.py
from django.urls import path

from admindashboard import views

urlpatterns = [

    # USER
    # path('all-users/', views.all_users),
    # path('view-all-users-admin/', views.all_users),
    # path('all-users/<str:layout>/', views.all_users),
    path('user-create/', views.add_new_user),
    path('view-all-users/', views.view_all_users),
    path('view-all-inactive-users/', views.view_inactive_users),
    path('edit-user/<str:id>/', views.update_user),
    path('send_credentials/<str:id>/', views.send_mail),
    path('delete-user/<str:id>/', views.delete_user),
    path('add_interviewee_detail/', views.Add_interviwe_detail),
    path('add_event/', views.Add_events),
    path("<str:action>/<str:id>/", views.Leave_Action),

    # path('view-single-user/<str:id>/', views.view_single_user),

    # PROGRAMMING LANGUAGE
    path('create-language/', views.add_programming_language),
    path('view-all-programming-language/', views.view_all_programming_language),
    path('edit-programming-language/<str:id>/',views.update_programming_language),
    path('delete-programming-language/<str:id>/', views.delete_programming_language),

    # TASK
    path('create-tasktype/',views.add_new_task_type),
    path('view-all-tasktype/',views.view_all_tasktype),
    path('edit-task-type/<str:id>/',views.update_task_type),
    path('delete-task-type/<str:id>/',views.delete_task_type),
    path('dummy_api/',views.my_django_view),

    # SYSTEM DETAIL
    path('create-system-details/', views.add_system_details),
    path('view-all-system-details/', views.view_all_system_details),
    path('edit-system-details/<str:system_id>/', views.update_system_details),
    path('delete-system-details/<str:system_id>', views.delete_system_details),
    # path('view-single-system-details/<str:pk>/', views.view_single_system_details),

    # ASSIGNED SYSTEM DETAIL
    path('create-assigned-system-details/', views.add_new_assigned_system_detail),
    path('view-all-assigned-system-details/', views.view_all_assigned_system_detail),
    # path('view-single-assigned-system-details/<str:id>', views.view_single_assigned_system_detail),
    path('edit-assigned-system-details/<str:id>/', views.update_assigned_system_details),
    path('delete-assigned-system-details/<str:id>/', views.delete_assigned_system_details),
    path('get-system', views.detail_assign_system, name="get-system"),
    # path('mail', views.birthday_messages, name="mail"),

    #ALL USER TASK
     path('view-all-user-task/', views.view_all_user_task),
     path('view-single-user-task/<str:id>', views.view_single_user_task),
     path('view-single-user-all-task/<str:user_id>', views.view_single_user_all_task),

    # ALL USER PROJECT
    path('view-all-user-project/', views.view_all_user_project),
    path('view-single-user-project/<str:project_id>', views.view_single_user_project),
    path('view-single-user-all-project/<str:user_id>',views.view_single_user_all_project),

    #VIEW CONTACT
    path('view-user-contact/', views.view_user_contact),
    # path('view/', views.abc),

    # VIEW ATTENDANCE
    path('view-all-user-attendance/', views.view_all_user_attendance),
    path('view-single-user-attendance/<str:user_id>', views.view_single_user_attendence),
    # path('view-chart',views.view_chart),
    path('view-today-all-attendence/', views.view_today_all_attendence),

    path('add-events/', views.add_events),
    path('view-events/', views.view_events),


    path('view-all-leave/', views.view_all_leave_detail),
    path('view-pending-leave/', views.view_pending_leave_detail),
    path('view-approved-leave/', views.view_approved_leave_detail),
    path('view-rejected-leave/', views.view_rejected_leave_detail),





]

core/urls.py
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from core import settings
from indexapp import views

from notification.views import showFirebaseJS

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('sentry-debug/', trigger_error),
    # path('admin/view-user-performance/<str:id>', views.view_chart),
    path('admin/', admin.site.urls),
    path('', views.index_view),
    path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.reset, name='reset'),
    path('password-forgot/', views.password_reset),
    path('dashboard/', include('dashboardapp.urls')),
    path('tasks/', include('taskapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('admin-dashboard/', include('admindashboard.urls')),
    path('notification/', include('notification.urls')),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('firebase-messaging-sw.js', showFirebaseJS, name="show_firebase_js"),
    path("admission-apply",views.apply_admission,name="appliction for admission")
    # path('view-chart',include('')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
   import debug_toolbar
   urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
   ]

admindashboard/models.py
from django.db import models

# Create your models here.

taskapp/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
import uuid
# Create your models here.
from projectapp.models import Project


class ProgrammingLanguage(models.Model):
    language_name=models.CharField(max_length=255)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.language_name

    class Meta:
        verbose_name = 'Languages / Department'

def get_upload_path(instance, filename):
    return 'profile_pictures/{0}/{1}'.format(instance.username, filename)

def get_upload_files_path(instance, filename):
    return 'files/{0}/{1}'.format(instance.task.user.username, filename)

def get_upload_display_profile_path(instance, filename):
    return 'display_profile/{0}/{1}'.format(instance.username, filename)

class User(AbstractUser):
    profile=models.ImageField(null=True,blank=True,upload_to=get_upload_display_profile_path)
    phone_number=models.CharField(max_length=10,null=True,blank=True)
    Alternate_phone_number=models.CharField(max_length=10,null=True,blank=True)
    office_user_id=models.CharField(max_length=255,null=True,blank=True)
    reporting_to=models.CharField(max_length=50,null=True,blank=True)
    is_employee=models.BooleanField(default=False)
    profile_updated=models.BooleanField(default=False)
    display_pic=models.ImageField(blank=True,null=True,upload_to=get_upload_path)
    joining_date=models.DateField(blank=True,null=True)
    leaving_date=models.DateField(blank=True,null=True)
    birthday=models.DateField(blank=True,null=True)
    programming_language=models.ForeignKey(ProgrammingLanguage,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.username


class Attendence(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    attend_date=models.DateField(auto_now_add=True)
    presence=models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Leave(models.Model):
    attendence = models.ForeignKey(Attendence, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    leave_period=models.CharField(max_length=20)
    leave_time=models.CharField(max_length=20,null=True,blank=True)
    start_date=models.DateField(auto_now_add=False)
    end_date=models.DateField(auto_now_add=False,null=True,blank=True)
    leave_type=models.CharField(max_length=30)
    leave_description=models.CharField(max_length=100,null=True,blank=True)
    is_pending=models.BooleanField(default=True)
    is_approved=models.BooleanField(default=False)
    is_rejected=models.BooleanField(default=False)



class Events(models.Model):
    title=models.CharField(max_length=30,null=True,blank=True)
    description=models.CharField(max_length=30,null=True,blank=True)
    start_date=models.DateField(auto_now_add=False)
    end_date=models.DateField(auto_now_add=False,null=True,blank=True)



class Detail_attendence(models.Model):
    attendence=models.ForeignKey(Attendence,on_delete=models.CASCADE,null=True,blank=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    punch_in=models.TimeField(null=True,blank=True)
    punch_out=models.TimeField(null=True,blank=True)
    attend_date=models.DateField(auto_now_add=True,null=True,blank=True)
    working_hours=models.CharField(max_length=30,null=True,blank=True)


class Reporting(models.Model):
    reported_by=models.CharField(max_length=30,null=True, blank=True)
    existing_reporting_to=models.CharField(max_length=30)
    new_reporting_to=models.CharField(max_length=30)
    duration_from=models.DateField(auto_now_add=False)
    duration_till=models.DateField(auto_now_add=False, null=True, blank=True)

class TaskType(models.Model):
     type_name=models.CharField(max_length=255)
     is_active=models.BooleanField(default=True)
     for_all=models.BooleanField(default=False)
     multiple_language = models.BooleanField(default=False)
     programming_language = models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE, null=True, blank=True)

     def __str__(self):
         return self.type_name

     class Meta:
         verbose_name = 'Task Type'

class multiple_select_language(models.Model):

    task_type=models.ForeignKey(TaskType,on_delete=models.CASCADE,null=True,blank=True)
    programming_language=models.ForeignKey(ProgrammingLanguage, on_delete=models.CASCADE, null=True, blank=True)


class Task(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    task_type=models.ForeignKey(TaskType,on_delete=models.CASCADE)
    title=models.CharField(max_length=255,default="",null=True,blank=True)
    project=models.ForeignKey(Project,on_delete=models.CASCADE,null=True,blank=True)
    details=models.TextField()
    added_on=models.DateTimeField(auto_now=True)
    updated_on=models.DateTimeField(null=True,blank=True)

    class Meta:

        ordering = ['-id']

    class Meta:
        verbose_name = 'Task'

class task_uploaded_file(models.Model):
     task = models.ForeignKey(Task,on_delete=models.CASCADE)
     uploaded_file = models.FileField(upload_to=get_upload_files_path)
     extension = models.CharField(max_length=255)



system_type_choices= [
        ("Computer", 'Computer'),
        ("Laptop", 'Laptop'),
        ("Macbook", 'MacBook'),
    ]

class  system_detail(models.Model):
    # created_on= models.DateTimeField()
    system_type = models.CharField(max_length=255,choices=system_type_choices,)
    specification = models.TextField()
    system_service = models.TextField(null=True,blank=True)
    system_id=models.CharField(max_length=255,primary_key=True)
    added_on=models.DateTimeField()
    status = models.CharField(max_length=50,default="Free")



    def __str__(self):
        return self.system_id

    class Meta:
        verbose_name = 'System Detail'

assigned_type_choices= [
        ("Temporary", 'Temporary'),
        ("Permanent", 'Permanent'),
    ]
class Assigned_System_Detail(models.Model):
    system_id=models.ForeignKey(system_detail,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    assigned_type = models.CharField(max_length=255, choices=assigned_type_choices, )
    assigned_on = models.DateField()
    returned_on=models.DateField(null=True,blank=True)

    class Meta:
        verbose_name = 'Assigned System Detail'

class Store_password(models.Model):
    password=models.CharField(max_length=255,null=True,blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Store Password'



import os
class Walk_in_Interviwee(models.Model):
    name=models.CharField(max_length=255,null=True,blank=True)
    interviwer_name=models.CharField(max_length=255,null=True,blank=True)
    profile=models.CharField(max_length=255,null=True,blank=True)
    experience=models.CharField(max_length=255,null=True,blank=True)
    date=models.DateField(null=True,blank=True)
    status=models.BooleanField(default=False)
    cv=models.FileField(upload_to='cv')

    def __str__(self):
        return self.name

    def __str__(self):
        name, extension = os.path.splitext(self.cv.name)
        return extension




class AddEvent(models.Model):
    title = models.CharField(max_length=25)
    created_at = models.DateField(auto_now=True)
    event_date = models.DateField()
    description = models.TextField(max_length=240)




class Event_photo(models.Model):
    addevent=models.ForeignKey('AddEvent',on_delete=models.CASCADE,null=True,blank=True)
    photo = models.ImageField(upload_to="event_images", null=True, blank=True)
    created_at = models.DateField(auto_now=True)

class Store_token(models.Model):
    user=models.CharField(max_length=255)
    token=models.TextField()
    device=models.CharField(max_length=255,null=True,blank=True)
    os=models.CharField(max_length=255,null=True,blank=True)


class Notification_record(models.Model):
    user=models.ForeignKey('User',on_delete=models.CASCADE,null=True,blank=True)
    created_at = models.DateField(auto_now=True)
    status=models.CharField(max_length=240)

templates/admindashboard/add_new_assigned_system_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin-dashboard/view-all-assigned-system-details/">All Assigned System Detail</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Assigned System Detail</a></li>
        </ol>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Assigned System Detail</h4>
            </div>
             {% if added %}
                <div class="alert alert-success alert-dismissible fade show">
                    <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <polyline points="9 11 12 14 22 4"></polyline>
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path>
                    </svg>
                    <strong>Success!</strong> System Assigned successfully.
                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                    </button>
                </div>
                {% endif %}
             {% if notadded %}
            <div class="alert alert-danger alert-dismissible fade show">
                  <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                      <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line></svg>
                  <strong>Error!</strong>System is Already Assigned! .
                  <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                                    </button>
                </div>
                {% endif %}
             {% if notaddeduser %}
            <div class="alert alert-danger alert-dismissible fade show">
                  <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                      <polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon>
                      <line x1="15" y1="9" x2="9" y2="15"></line>
                      <line x1="9" y1="9" x2="15" y2="15"></line></svg>
                  <strong>Error!</strong>User has already a system! .
                  <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                                    </button>
                </div>
                {% endif %}


            <div class="card-body">
                <div class="basic-form">
<!--                    <form method="post" enctype="multipart/form-data">-->

                        <form method="POST" class="post-form"  enctype="multipart/form-data" id="personForm" data-cities-url="{% url 'get-system' %}">
                          {% csrf_token %}
                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">System</label>
                            <div class="col-sm-9">
                                <select class="form-control "  name="sys_id"  id="id_system_id" required>
                                     <option value="">---------</option>
                                    {%for detail in systemdetail%}

                                        <option value="{{detail.system_id}}">{{detail.system_type}}</option>
                                        {% endfor %}
                                    </select>
                                   <div id="er"></div>
                                   <div id="sysnotadd">
                                       {% if sysnotadd %}
                                    <div class="alert alert-warning alert-dismissible fade show mt-1 " >
                                     {{form.system_id.errors}}

                                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                                    </button>

                                    </div>
                                {% endif %}
                                   </div>
                            </div>
                         </div>
                            <div id="system_id" class="col-md-6">
                                </div>

                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Assigned To</label>
                            <div class="col-sm-9">
                                <select class="form-control "  name="user"  id="id_user" required>
                                     <option value="">---------</option>
                                    {%for person in user%}

                                        <option value="{{person.id}}">{{person.username}}</option>
                                        {% endfor %}
                                    </select>
                                <div id="er1"></div>

                                <div id="usererror">
                                     {% if notadd %}
                                    <div class="alert alert-warning alert-dismissible fade show mt-1 " >
                                     {{form.user.errors}}
                                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                                    </button>
                                    </div>
                                {% endif %}
                                </div>
                            </div>
                         </div>

                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Assigned Type</label>
                            <div class="col-sm-9">
                                <select class="form-control"  name="assigned_type" id="id_assigned_type" required>
                                    <option value="">--------</option>
                                    <option value="temporary">Temporary</option>
                                    <option value="permanent">Permanent</option>
                                </select>
                                <div id="er2"></div>

                                <div id="typerror">

                                </div>
                            </div>
                         </div>

                         <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Assigned On</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="assigned_on" placeholder="Enter Assigned On"  required>
                            </div>
                        </div>

                          <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Returned On</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" name="returned_on" placeholder="Enter Returned On">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="container">
                                <div class="btn-block d-sm-flex justify-content-end">
                                     <button type="submit" class="btn btn-sm btn-primary" onclick="save()">SAVE</button>&nbsp;
                                     <button type="reset" class="btn btn-sm btn-warning">CANCEL</button>

                             </div>
                           </div>
                        </div>
                        <!-- <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Joined Date</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" value="{{request.user.programming_language.language_name}} " readonly>
                                            </div>
                                        </div> -->

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

function save(){
var a=document.getElementById("id_system_id").value;
var b=document.getElementById("id_user").value;
var c=document.getElementById("id_assigned_type").value;
var d=document.getElementById("sysnotadd").innerHTML;
var e=document.getElementById("usererror").innerHTML;
var f=document.getElementById("typerror").innerHTML;
console.log(f);
console.log(f.length)
if(a==0){
if(d.length==76){
document.getElementById("er").classList.add('alert','alert-warning',"mt-2,'err'");
document.getElementById("er").innerHTML='this field is required <button type="button" class="close h-100" aria-label="Close"><span><i class="mdi mdi-close"></i></span></button>';
return false;
}
}
else{
document.getElementById("er").classList.remove('alert','alert-warning',"mt-2");
document.getElementById("er").innerHTML="";
}

if(b==0){
if(e.length==71){
document.getElementById("er1").classList.add('alert','alert-warning',"mt-2");
document.getElementById("er1").innerHTML='this field is required<button type="button" class="close h-100" aria-label="Close"><span><i class="mdi mdi-close"></i></span></button>';
return false;
}
}
else{
document.getElementById("er1").classList.remove('alert','alert-warning',"mt-2");
document.getElementById("er1").innerHTML="";
}

if(c==0){
document.getElementById("er2").classList.add('alert','alert-warning',"mt-2");
document.getElementById("er2").innerHTML='this field is required <button type="button" class="close h-100" aria-label="Close"><span><i class="mdi mdi-close"></i></span></button>';
return false;
}
else{
document.getElementById("er2").classList.remove('alert','alert-warning',"mt-2");
document.getElementById("er2").innerHTML="";
}

}

$("#er").click(function(){
    console.log("ok");
    $("#er").toggleClass();
    $(this).html('');
});
$("#er1").click(function(){
    console.log("ok");
    $(this).toggleClass();
    $(this).html('');
});
$("#er2").click(function(){
    console.log("ok");
    $(this).toggleClass();
    $(this).html('');
});

</script>
<script>

var exp;
    $("#id_system_id").change(function () {
      var url = $("#personForm").attr("data-cities-url");
      exp = $(this).val();
      console.log('here',exp)


     $.ajax({
        url: url,
        type:"GET",
        data: {

          'system': exp
        },
        success: function (data) {
          $("#system_id").html(data);

          }
      });
      });

</script>
{% endblock %}

templates/admindashboard/add_programming_language.html
{% extends 'base.html' %}
{% block content %}
<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/dashboard/">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="/admin-dashboard/view-all-programming-language/">Department</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0)">Add</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Department Name</h4>
            </div>
             {% if added %}
                <div class="alert alert-success alert-dismissible fade show">
                    <svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <polyline points="9 11 12 14 22 4"></polyline>
                        <path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path>
                    </svg>
                    <strong>Success!</strong> Department added successfully.
                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                    </button>
                </div>
                {% endif %}

            <div class="card-body">
                <div class="basic-form">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Department Name</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control text-capitalize" name="language_name"  placeholder="Enter here" required>
<!--                           {{form.language_name.errors}}-->
                                    {% if notadd %}
                                    <div class="alert alert-warning alert-dismissible fade show">
                                    {{form.language_name.errors}}
                                    <button type="button" class="close h-100" data-dismiss="alert" aria-label="Close"><span><i class="mdi mdi-close"></i></span>
                                    </button>
                                    </div>
                                    {% endif %}
                            </div>
                        </div>

                        <div class="form-group row">
                             <div class="container">
                                <div class="btn-block d-sm-flex justify-content-end">
                                     <button type="submit" class="btn btn-sm btn-primary">SAVE</button>&nbsp;
                                    <button type="reset"  class="btn btn-sm btn-warning">CANCEL</button>

                                </div>
                            </div>
                        </div>
                        <!-- <div class="form-group row">
                                            <label class="col-sm-3 col-form-label">Joined Date</label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" value="{{request.user.programming_language.language_name}} " readonly>
                                            </div>
                                        </div> -->
                    </form>
                </div>
            </div>
             <div class="login_foot border-top pt-4">
                <p class="text-center mb-0">©SurajKuikel Copyright. All right reserved.</p>
              </div>
        </div>
    </div>
</div>








{% endblock %}
{% block js %}
<script>
// Add the following code if you want the name of the file appear on select
$(".custom-file-input").on("change", function() {
    var fileName = $(this).val().split("\\").pop();
    $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
{% endblock %}

templates/admindashboard/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href=http://www.uptaskdemo.visiontrek.in>click here to login </a>
<p><span>Hi {{username}}</span><br><br>Your username is :  {{username}} <br>Your password is :  {{password1}}&nbsp;<br></p>

<p>Regards</p>

<p>Visiontrek Communications</p>



</body>
</html>